puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"

puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"

puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"

puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"

puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"
puts "this is a thing thing"

